version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/html/tt/public
permissions:
   - object: /var/www/html/tt/public
     pattern: "**"
     owner: www-data
     group: www-data
     mode: 644
     type:
       - file
   - object: /var/www/html/tt/public
     pattern: "**"
     owner: www-data
     group: www-data
     mode: 755
     type:
       - directory
hooks:
   ApplicationStart: 
    - location: codedeploy/restart_server.sh
      timeout: 300
      runas: root       
