version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/html/tt/public
permissions:
   - object: /var/www/html/tt/public
     pattern: "**"
     owner: www-data
     group: www-data
     mode: 644
     type:
       - file
   - object: /var/www/html/tt/public
     pattern: "**"
     owner: www-data
     group: www-data
     mode: 755
     type:
       - directory
hooks:
  BeforeInstall:
    - location: codedeploy/stop_server
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: codedeploy/stop_server
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: codedeploy/start_server
      timeout: 300
      runas: ubuntu
  ApplicationStart: 
    - location: codedeploy/start_server
      timeout: 300
      runas: ubuntu       
