version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/html/test
permissions:
   - object: /var/www/html/test
     pattern: "**"
     owner: www-data
     group: www-data
     mode: 644
     type:
       - file
   - object: /var/www/html/test
     pattern: "**"
     owner: www-data
     group: www-data
     mode: 755
     type:
       - directory